// Write a program with the string data type in cpp

#include <iostream>
using namespace std;

int main()
{
    // Declare a variable with the string data type
    string name;

    // Take input from the user
    cout << endl << "Enter your name : ";
    cin >> name;

    // Printing a message for the user
    cout << endl << "Hello " << name << ", Thank you for your response..." << endl << endl ;
    
    return 0;
}